### ISSUE TITLE
Cannot launch the map and rosplan

### ISSUE THREAD

**Issue by yin1008** [laperss/wasp_search_and_rescue#1]
Hi, laperss @laperss ,
Thanks for your great work. I'm pretty interested in navigation method to combine the tag based positioning and SLAM. I have a AR drone 2.0 available now and I want to repeat your work.

But when I compile the source code, an error occurred  that:
Assertion failed: file /wasp_search_and_rescue/drone/srv/StringService.srv'  does not exist.  Message: service file not found. 

Then I checked the folder of  /wasp_search_and_rescue/drone/, there was not the folder named 'srv'. Could you please tell me what to do next? Thanks a lot.

By Yin
31/03/18

**Comment by yin1008** [comment]
OK  now. I switched to the other branch and it worked. Thanks anyway. I will keep update my progress.

**Comment by yin1008** [comment]
But after I switched to branch mocap, The folder of  tag_position was missed. Should I just add the folder from master branch?

**Comment by yin1008** [comment]
But after I switched to branch mocap, The folder of tag_position was missed. Should I just add the folder from master branch?

**Comment by yin1008** [comment]
I cannot repeat your work by the instructions in README.md. Could you please make it clear? I cannot even launch the map. Thanks.

**Comment by yin1008** [comment]
When trying run_planner.sh, another error happend:
 raise ResourceNotFound(name, ros_paths=self._ros_paths)
ResourceNotFound: rosplan_config
ROS path [0]=/opt/ros/indigo/share/ros
ROS path [1]=/home/yhh/ardrone/src
ROS path [2]=/opt/ros/indigo/share
ROS path [3]=/opt/ros/indigo/stacks
Add knowledge
Waiting for services to start...
Launch rqt
Run planner
ERROR: Service [/kcl_rosplan/planning_server] is not available.

Could you please help me with this problem?

**Comment by laperss** [comment]
This looks like an error with running the [kcl_rosplan](http://kcl-planning.github.io/ROSPlan/documentation/planning_system_use.html) package. What version of ROS are you using? I believe this package only works with indigo but you should check their description. 

The branch mocap is if you are using a motion capture system for localization instead of the apriltags that are described in the README. So unless you are using some other kind of motion capture system you should be on the master branch.

**Comment by laperss** [comment]
I was working on the mocap branch last week but somehow it looks like I deleted the stringservice from the wrong branch. This should be fixed now, as I added the StringService again.

**Comment by laperss** [comment]
I have not experienced this but I used an old version of ROSplan from 2016. 

Someone with the same problem as you describes it here: [https://github.com/KCL-Planning/ROSPlan/issues/40](https://github.com/KCL-Planning/ROSPlan/issues/40)

It looks like the ROSplan package used to have the folder "rosplan_config" but that it is now missing for some reason (you can still see it in other branches), and that your node is not correctly started for this reason. 
You should probably ask the developers of ROSplan about this error.

**Comment by yin1008** [comment]
It is of great help for me. Now I switched to another version (final viewer) of ROSPlan. And the previous error disappeared.  However, there is another problem when I roslaunch the file start_planning_system.launch. I got the message below:

ResourceNotFound: drone_planning

After I checked the file start_planning_system.launch, the package of drone_planning is absent. I guess you forgot to upload that folder, right? Could you please update your file?

Based  on your great work, I want to implement the the Apriltag recognition with a newer SLAM——
ORB-SLAM2. It will be appreciated if you could give some suggestions about the adaptation of the code. I need to subscribe the /pos_scaled from the SLAM node?

Thanks!

**Comment by laperss** [comment]
The file [start_planning_system.launch](https://github.com/laperss/wasp_search_and_rescue/blob/master/planning/launch/start_planning_system.launch) is just the file [interfaced_planning_system.launch](https://github.com/KCL-Planning/ROSPlan/blob/a1d4c42483a2d4c1fa5eaa1e319836b85f394fb0/rosplan_planning_system/launch/interfaced_planning_system.launch) with a change of what domain file it is referring to. 
If you just change the line to 
```
<param name="/rosplan/domain_path" value="$(find rosplan_config)/planner/domain.pddl" />
```
It should load the "original" domain file (given that you have the correct version of ROSplan. I put my domain file in the wiki in case you are interested in using it instead, however, it was very specific to the demonstration we were doing. 

If the only thing you need is Apriltag recognition I believe you could do it without this package, since the objective here was to use the tags for positioning. Maybe have a look at the apriltag package instead!

**Comment by yin1008** [comment]
Thanks for your help and I can repeat your project now.
